name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2-texlive2022
        with:
          root_file: piotr_migdal_resume.tex
      - name: Copy generated files
        run: |
          mkdir output
          cp piotr_migdal_resume.pdf output/
          cp piotr_migdal_resume.bbl output/
          cp piotr_migdal_resume.log output/
          cp piotr_migdal_resume.blg output/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: output
          FOLDER: output
